language: php

php:
  - '7.0'

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: composer install

before_script:
  - mkdir -p build/logs

after_success:
  - php vendor/bin/coveralls -v